Story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
     path('story1/', include('story1.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('Hobbies/', views.Hobbies, name='Hobbies'),
    path('game/', views.game, name='game'),
    path('contact/', views.contact, name='contact'),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here
def home(request):
    return render(request, 'home.html')

def aboutme(request):
    return render(request, 'aboutme.html')

def contact(request):
    return render(request, 'contact.html')

def game(request):
    return render(request, 'game.html')

def Hobbies(request):
    return render(request, 'Hobbies.html')

# diteruskan...

story1/views.py
from django.shortcuts import render

def story1(request):
    return render(request, 'story1.html')

main/templates/main/home.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="style.css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
      </head>
<body background="https://images.unsplash.com/photo-1563089145-599997674d42?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80">
    
    <nav class="navbar navbar-inverse"style= "margin-bottom: 0; ">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand"> <img class="img-responsive" src="https://i.ibb.co/3YdJXQ9/message-Image-1600948195137-removebg-preview.png" width = "20" height = "auto" ></a>
          </div>
          
          <ul class="nav navbar-nav">
            <li class="active"><a href="home.html">Home</a></li>
            <li><a href="aboutme.html">About me</a></li>
            <li><a href="game.html">Game</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
    </nav>

      <div class = "fotohome1">
      <a href = "aboutme.html"><img class="img-responsive" src="https://i.ibb.co/hB2XxJ1/message-Image-1600948361210.jpg" style="display: block; margin: auto; border-radius: 20px;"width="300px" ></a>
      </div>
      <div class="footer-home">
        <p><b>Copyright @ 2020 Robby</b></p>
      </div>
</body>
</html>

story1/templates/story1.html
<!DOCTYPE html>
<html lang = "en">
<head>
</head>
<style>
    body {  background: black;
        color:whitesmoke;
        height : "100%";
        font-size: 16px;
        border: 2px solid rgb(90, 102, 209);
        font-family: verdana;
         }
         img {
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .parallax {
            background-image: url("https://i.ibb.co/hYN8Kjx/526173.jpg");
            min-height: 1000px; 
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            margin-bottom: 30px;
        }

    

</style>
<body>
    {% include "navbar.html" %}
  
    <div class="parallax"></div>
    <div style="text-align: center; background-color: black;">

        <a href="https://ibb.co/2kCdt43"><img src="https://i.ibb.co/2kCdt43/message-Image-1600697583150.jpg" height = 250></a><br>
    
    <table style="width:40%" align="center" border= "1">
        <tr>
            <td>Name</td>
            <td>: Robby</td>
        </tr>
        <tr>
            <td>NPM</td>
            <td>: 1906400381</td>
        </tr>
        <tr>
            <td>Student of</td>
            <td>: Fasilkom UI 2019 </td>
        </tr>
        <tr>
            <td>Hobbies</td>
            <td>: Basketball</td>
        </tr>
        <tr>
            <td>Find me on maung website</td>
            <td>Visit <a href="https://maung.id/">maung.id </a></td>
        </tr>
  
    </table>

    <h1 style="font-size:30px;">Education Details</h1>

    <table style="width:40%" border = "1" align="center">
        <tr>
            <td>Junior high school state 216 Jakarta</td>
            <td>2013-2016</td>
        </tr>
        <tr>
            <td>Senior high school state 59 Jakarta</td>
            <td>2016-2019</td>
        </tr>
        <tr>
            <td>University of Indonesia</td>
            <td>2019-2023 (expected)</td>
        </tr>

    </table>
    <h1 style = "font-size: 23px;">one sentence about me: <h1>
    <h1 style = "font-size: 20px;">An ordinary person who have ambition</h1>
    </div>
    <h1 style="font-size:30px;">Let's be friend on :</h1>
    <table style="width:20%" >
        <tr>
            <td><a href="https://www.instagram.com/nfrobby/?hl=id"><img src="https://i.ibb.co/S5S1VJy/ig.png" target="_blank" height="50" width="50"></a></td>
            <td><a href="https://www.linkedin.com/in/robby-nur-fadillah-183897157/"><img src="https://i.ibb.co/dr8rjcK/linkedin.png"target="_blank"  height="60" width="60"></a></td>
            <td><a href="https://twitter.com/Nfrobby1"><img src="https://i.ibb.co/NLh0nBk/twitter.png"target="_blank"  height="60" width="60"></a><td>
            <td><a href="https://steamcommunity.com/id/a7xjnr"><img src="https://i.ibb.co/RY1QDrQ/steam.png" target="_blank" height="46" width="46"></a></td>
           

        </tr>
            </table>
    


</body>
</html>

templates/Hobbies.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="static https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins&display=swap">
  </head>

<body>
    <div class = "backgroundcolor">
    
      {% include "navbar.html" %}
      <a href = "https://id.wikipedia.org/wiki/Kyrie_Irving"><img class="img-responsive" width = 100% src="https://i.ibb.co/Jv8Bmy3/kyrieirving.jpg" target="_blank" ></td></a>
      <a href = "https://id.wikipedia.org/wiki/LeBron_James"><img class="img-responsive" width = 100% src="https://i.ibb.co/jhjwvH0/Le-Bron-James-1200-1.jpg" target="_blank" ></td></a>
      <a href = "https://id.wikipedia.org/wiki/Kobe_Bryant"><img class="img-responsive" width = 100% src="https://i.ibb.co/rvFwCvt/kobe-background-8.jpg" target="_blank" ></td></a>
      <div class = "footer">
        <p align="center"><b>Copyright @ 2020 Robby</b></p>
      </div>
      </div>
</body>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
<p>pls bisa</p>
  {% block content %}
  {% endblock content %}
</html>

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
      <head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="static https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins&display=swap">

      </head>

<body background="https://wallpaperaccess.com/full/512679.jpg">
 
  
    {% include "navbar.html" %}
      <a><img class="img-responsive" width = 100% src="https://i.ibb.co/JcD2L17/message-Image-1601707308638-1.jpg"></td></a>
     
      </table>
      <div class = "footer">
        <p align="center"><b>Copyright @ 2020 Robby</b></p>
      </div>

</body>
</html>

templates/game.html
{% load static %}
<!DOCTYPE html>
<html>
        <head>
          <head>
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
          <script src="static https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins&display=swap">
        </head>

<body>
    <div class = "backgroundcolor">
   
      {% include "navbar.html" %}
      <a href = "https://www.ea.com/games/apex-legends"><img class="img-responsive" width = 100% src="https://cdnb.artstation.com/p/assets/images/images/029/448/513/medium/fahx-pv-apex-legends-season-6-4k-wallpaper2lag.jpg?1597593446"target="_blank"></td></a>
      <a href = "https://www.ea.com/games/apex-legends"><img class="img-responsive" width = 100% src="https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/08/Apex-Legends-Season-6-trailer-Lifeline.jpg"target="_blank"></td></a>
      <a href = "https://www.ea.com/games/apex-legends"><img class="img-responsive" width = 100% src="https://i.redd.it/zy5fw89n1jq41.png"target="_blank"></td></a>
      <div class = "footer">
        <p align="center"><b>Copyright @ 2020 Robby</b></p>
      </div>
      </div>    
      
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="style.css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
      </head>
<body background="https://images.unsplash.com/photo-1563089145-599997674d42?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80">
    
  {% include "navbar.html" %}

      <div class = "fotohome1">
      <a href = "aboutme.html"><img class="img-responsive" src="https://i.ibb.co/hB2XxJ1/message-Image-1600948361210.jpg" style="display: block; margin: auto; border-radius: 20px;"width="300px" ></a>
      </div>
      <div class="footer-home">
        <p><b>Copyright @ 2020 Robby</b></p>
      </div>
</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
        <head>
          <link rel="stylesheet" href="{% static 'css/style.css' %}">
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
          <script src="static https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins&display=swap">
        </head>
<style></style>

</style>
<body style="padding: 0px;margin: 0px;">
    <nav class="navbar navbar-inverse" style= "margin-bottom: 0;">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand"> <img class="img-responsive"  src="https://i.ibb.co/3YdJXQ9/message-Image-1600948195137-removebg-preview.png" width = "20" height = "auto" ></a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'main:home' %}">Home</a></li>
            <li><a href="{% url 'main:aboutme' %}">About me</a></li>
            <li><a href="{% url 'main:game' %}">Game</a></li>
            <li><a href="{% url 'main:contact' %}">Contact</a></li>
            <li><a href="{% url 'story1:story1' %}">Story1</a></li>
          </ul>
        </div>
      </nav>
</body>
</html>